- Effect: Allow
  Action:
    - dynamodb:CreateTable
    - dynamodb:Query
    - dynamodb:Scan
    - dynamodb:GetItem
    - dynamodb:PutItem
    - dynamodb:UpdateItem
    - dynamodb:DeleteItem
    - dynamodb:DescribeTable
  Resource:
    - Fn::GetAtt: [StKeyTable, Arn]
    - Fn::GetAtt: [QuestionTable, Arn]
    - Fn::Sub: "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${QuestionTable}/index/stKeyIdIndex"